name: Build Unity PC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Unity
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
        restore-keys: |
          Library-${{ runner.os }}-
          Library-

    - name: Unity - Builder
      uses: game-ci/unity-builder@v4.5.0
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        unityVersion: 6000.2.4f1   # Your Unity version
        targetPlatform: StandaloneWindows64

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build
